---
- name: dotfiles | make ~/.config
  file: path=~/.config state=directory

- name: dotfiles | create backup directory
  file: path=~/.backups state=directory

- name: dotfiles | create symlinks
  file: src={{ ansible_env.PWD }}/roles/dotfiles/files/{{ item }}
        path=~/{{ item }}
        state=link
        force=yes
  with_items: '{{dotfile_files}}'
