window:
  # Spread additional padding evenly around the terminal content.
  dynamic_padding: true
  decorations: buttonless

  startup_mode: Windowed

  # Window title
  title: Alacritty

scrolling:
  history: 0

# Font configuration
font:
  normal:
    family: JetBrainsMono Nerd Font Mono
    style: Regular

  bold:
    family: JetBrainsMono Nerd Font Mono
    style: Bold

  italic:
    family: JetBrainsMono Nerd Font Mono
    style: Italic

  bold_italic:
    family: JetBrainsMono Nerd Font Mono
    style: Bold Italic

  size: 11.0
  offset:
    x: 1
    y: 0
  glyph_offset:
    x: 0
    y: 1
  use_thin_strokes: true

draw_bold_text_with_bright_colors: false

colors:
  primary:
    background: "#1B2B34"
    foreground: "#C0C5CE"

  cursor:
    text: "#1B2B34"
    cursor: "#ffffff"

  normal:
    black: "#18252C"
    red: "#EA606A"
    green: "#9AC696"
    yellow: "#F9C76B"
    blue: "#689ACA"
    magenta: "#C495C4"
    cyan: "#62B3B2"
    white: "#FFFFFF"

  bright:
    black: "#455477"
    red: "#EA606A"
    green: "#9AC696"
    yellow: "#F9C76B"
    blue: "#689ACA"
    magenta: "#C495C4"
    cyan: "#62B3B2"
    white: "#ffffff"

visual_bell:
  duration: 0

background_opacity: 1.0

selection:
  save_to_clipboard: true

dynamic_title: true

cursor:
  style: Block
  unfocused_hollow: true

live_config_reload: true
alt_send_esc: false

mouse:
  hide_when_typing: true
  url:
    launcher:
      program: open
      args: []
    modifiers: Command

# Mouse bindings
mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

# Key bindings
key_bindings:
  - { key: Key0, mods: Command, action: ResetFontSize }
  - { key: Equals, mods: Command, action: IncreaseFontSize }
  - { key: Add, mods: Command, action: IncreaseFontSize }
  - { key: Minus, mods: Command, action: DecreaseFontSize }
  - { key: K, mods: Command, action: ClearHistory }
  - { key: V, mods: Command, action: Paste }
  - { key: C, mods: Command, action: Copy }
  - { key: H, mods: Command, action: Hide }
  - { key: M, mods: Command, action: Minimize }
  - { key: Q, mods: Command, action: Quit }
  - { key: W, mods: Command, action: Quit }
  - { key: N, mods: Command, action: SpawnNewInstance }
  - { key: F, mods: Command|Control, action: ToggleFullscreen }
